export const TRIGGER = {
    SELECT_DOCUMENT: 'SELECT_DOCUMENT',
    FILE_UPLOADED: 'FILE_UPLOADED',
    DELETE_DOCUMENT: 'DELETE_DOCUMENT',
    ALERT: 'ALERT',
    SELECT_COLLECTION: 'SELECT_COLLECTION',
}