"""Change AppMetrics model

Revision ID: 0e51ab5bf3a7
Revises: 128f80f51883
Create Date: 2025-06-16 05:54:38.593915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e51ab5bf3a7'
down_revision: Union[str, None] = '128f80f51883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_metrics', sa.Column('last_file_name', sa.String(), nullable=True))
    op.add_column('app_metrics', sa.Column('last_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_metrics', 'last_file_path')
    op.drop_column('app_metrics', 'last_file_name')
    # ### end Alembic commands ###
