"""Add AppMetrics model

Revision ID: 128f80f51883
Revises: a61567dc9d8b
Create Date: 2025-06-16 05:52:24.482818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128f80f51883'
down_revision: Union[str, None] = 'a61567dc9d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('files_processed', sa.Integer(), nullable=True),
    sa.Column('min_time_processed', sa.Float(), nullable=True),
    sa.Column('avg_time_processed', sa.Float(), nullable=True),
    sa.Column('max_time_processed', sa.Float(), nullable=True),
    sa.Column('latest_file_processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_user_id', sa.Integer(), nullable=True),
    sa.Column('last_user_name', sa.String(), nullable=True),
    sa.Column('last_file_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_metrics_id'), 'app_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_metrics_id'), table_name='app_metrics')
    op.drop_table('app_metrics')
    # ### end Alembic commands ###
