"""remove pwc code

Revision ID: 2b546f860018
Revises: 63a1371473a7
Create Date: 2025-06-16 02:37:50.599694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b546f860018'
down_revision: Union[str, None] = '63a1371473a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwc_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwc_code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
