"""add document hash

Revision ID: a61567dc9d8b
Revises: 2b546f860018
Create Date: 2025-06-16 03:05:51.933316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61567dc9d8b'
down_revision: Union[str, None] = '2b546f860018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
