"""add text to Document Word

Revision ID: bb126cba6424
Revises: ea0a567a04da
Create Date: 2025-04-27 14:49:41.558345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb126cba6424'
down_revision: Union[str, None] = 'ea0a567a04da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_words', sa.Column('text', sa.String(), nullable=True))
    op.create_index(op.f('ix_document_words_text'), 'document_words', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_words_text'), table_name='document_words')
    op.drop_column('document_words', 'text')
    # ### end Alembic commands ###
