"""add pwc code

Revision ID: d0cec9122acc
Revises: 9884a8f665f5
Create Date: 2025-06-04 17:54:40.529053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cec9122acc'
down_revision: Union[str, None] = '9884a8f665f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwc_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwc_code')
    # ### end Alembic commands ###
