"""fix_unique

Revision ID: d892e7bc9bb1
Revises: bb126cba6424
Create Date: 2025-04-27 14:58:23.335973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd892e7bc9bb1'
down_revision: Union[str, None] = 'bb126cba6424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_words_text', table_name='document_words')
    op.create_index(op.f('ix_document_words_text'), 'document_words', ['text'], unique=False)
    op.drop_index('ix_words_text', table_name='words')
    op.create_index(op.f('ix_words_text'), 'words', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_text'), table_name='words')
    op.create_index('ix_words_text', 'words', ['text'], unique=True)
    op.drop_index(op.f('ix_document_words_text'), table_name='document_words')
    op.create_index('ix_document_words_text', 'document_words', ['text'], unique=True)
    # ### end Alembic commands ###
