services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7
    container_name: nginx-proxy
    ports:
      - "${NGINX_PORT_HTTP}:${NGINX_PORT_HTTP}"
      - "${NGINX_PORT_HTTPS}:${NGINX_PORT_HTTPS}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

      - /home/ubuntu/nginx-proxy-data/certs:/etc/nginx/certs
      - /home/ubuntu/nginx-proxy-data/vhost.d:/etc/nginx/vhost.d
      - /home/ubuntu/nginx-proxy-data/html:/usr/share/nginx/html

    labels:
      com.github.nginx-proxy.nginx: "true"
      
    networks:
      - tf_idf_network
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory #тестовые не валидные сертификаты
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - /home/ubuntu/nginx-proxy-data/certs:/etc/nginx/certs
      - /home/ubuntu/nginx-proxy-data/vhost.d:/etc/nginx/vhost.d
      - /home/ubuntu/nginx-proxy-data/html:/usr/share/nginx/html
    networks:
      - tf_idf_network
    restart: always

networks:
  tf_idf_network:
    external: true
