services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
    container_name: tf_idf_lesta_frontend
    expose:
      - "${FRONTEND_VIRTUAL_PORT}"
    ports:
      - "${FRONTEND_VIRTUAL_PORT}:${FRONTEND_VIRTUAL_PORT}"  
    environment:
      - VIRTUAL_HOST=${FRONTEND_VIRTUAL_HOST}
      - VIRTUAL_PORT=${FRONTEND_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${FRONTEND_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: always
    networks:
      - tf_idf_network
      - network_frontend

networks:
  network_frontend:
    driver: bridge
  tf_idf_network:
    external: true