version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DOMAIN: http://37.9.53.221:8000
    container_name: tf_idf_lesta_frontend
    ports:
      - "3000:3000"

    restart: always
    networks:
      - tf_idf_network

networks:
  tf_idf_network:
    driver: bridge