services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DOMAIN: https://app.grenka.uz
    container_name: tf_idf_lesta_frontend
    restart: always
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=grenka.uz,www.grenka.uz
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grenka.uz
      - LETSENCRYPT_EMAIL=you@example.com  # ← замени на свой email
    networks:
      - tf_idf_network

networks:
  tf_idf_network:
    driver: bridge