version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tf_idf_lesta_frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge