services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DOMAIN: https://app.grenka.uz
    container_name: tf_idf_lesta_frontend
    ports:
      - "3000:3000"

    restart: always
    networks:
      - tf_idf_network

networks:
  tf_idf_network:
    driver: bridge