version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tf_idf_lesta_frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_DOMAIN=http://tf_idf_lesta:8000
    restart: always
    networks:
      - tf_idf_network

networks:
  tf_idf_network:
    driver: bridge