services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DOMAIN: https://app.grenka.uz
    container_name: tf_idf_lesta_frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"  
    environment:
      - VIRTUAL_HOST=grenka.uz,www.grenka.uz
      - VIRTUAL_PORT=3000
    restart: always
    networks:
      - tf_idf_network

networks:
  tf_idf_network:
    external: true