version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DOMAIN: http://localhost:8001
    container_name: tf_idf_lesta_frontend
    ports:
      - "3001:3000"

    restart: always
    networks:
      - tf_idf_network

networks:
  tf_idf_network:
    driver: bridge