name: Deploy Backend and Frontend (main only)

on:
  push:
    branches:
      - main  # только ветка main триггерит CI

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Docker network exists
        run: |
          if ! docker network inspect tf_idf_network >/dev/null 2>&1; then
            docker network create tf_idf_network
          fi

      # NGINX
      - name: Sync nginx_proxy files
        run: |
          mkdir -p /home/ubuntu/nginx_proxy
          rsync -av --delete ./nginx_proxy/ /home/ubuntu/nginx_proxy/

      - name: Create Nginx-proxy .env
        run: |
          cat <<EOF > /home/ubuntu/nginx_proxy/.env
          ${{ secrets.NGINX_ENV }}
          EOF

      # BACKEND
      - name: Sync backend files
        run: |
          mkdir -p /home/ubuntu/lesta_tz_backend
          rsync -av --delete ./lesta_tz_backend/ /home/ubuntu/lesta_tz_backend/

      - name: Create Backend .env
        run: |
          cat <<EOF > /home/ubuntu/lesta_tz_backend/.env
          ${{ secrets.ENV_FILE }}
          EOF

        # FRONTEND
      - name: Sync frontend files
        run: |
          mkdir -p /home/ubuntu/lesta_tz_frontend
          rsync -av --delete ./lesta_tz_frontend/ /home/ubuntu/lesta_tz_frontend/

      - name: Create frontend .env
        run: |
          cat <<EOF > /home/ubuntu/lesta_tz_frontend/.env
          ${{ secrets.FRONTEND_ENV }}
          EOF

      # DEPLOY
      - name: Deploy nginx-proxy
        run: |
          cd /home/ubuntu/nginx_proxy
          docker compose down
          docker compose up -d --build

      - name: Deploy backend
        run: |
          cd /home/ubuntu/lesta_tz_backend
          docker compose down
          docker compose up -d --build

      - name: Deploy frontend
        run: |
          cd /home/ubuntu/lesta_tz_frontend
          docker compose down
          docker compose up -d --build