name: Deploy Backend and Frontend (main only)

on:
  push:
    branches:
      - main  # только ветка main триггерит CI

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy backend files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "lesta_tz_backend/"
          target: "/home/ubuntu"

      - name: Copy frontend files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "lesta_tz_frontend/"
          target: "/home/ubuntu"

      - name: Create .env on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cat <<EOF > /home/ubuntu/lesta_tz_backend/.env
            ${{ secrets.ENV_FILE }}
            EOF

      - name: Ensure Docker network exists
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! sudo docker network inspect tf_idf_network >/dev/null 2>&1; then
              sudo docker network create tf_idf_network
            fi

      - name: Clean up unused Docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker image prune -a -f

      - name: Deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/lesta_tz_backend
            sudo docker compose down
            sudo docker compose up -d --build

      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/lesta_tz_frontend
            sudo docker compose down
            sudo docker compose up -d --build
