services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    networks:
      - tf_idf_network
      - nginx_proxy
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=haratian.gena@gmail.com
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - tf_idf_network
      - nginx_proxy
    restart: always

  db:
    image: postgres
    container_name: tf_idf-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tf_idf_network
      - nginx_proxy

  web:
    build: .
    container_name: tf_idf_lesta
    environment:
      - VIRTUAL_HOST=app.grenka.uz
      - LETSENCRYPT_HOST=app.grenka.uz
      - LETSENCRYPT_EMAIL=haratian.gena@gmail.com
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ALLOW_ORIGINS=${ALLOW_ORIGINS}
    volumes:
      - alembic-data:/app/alembic/versions
      - static-data:/app/static
    depends_on:
      - db
    command: >
      sh -c "/wait-for-it.sh db:${DB_PORT} -- alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips=${ALLOW_ORIGINS}"
    networks:
      - tf_idf_network
      - nginx_proxy
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - VIRTUAL_HOST=portainer.grenka.uz
      - LETSENCRYPT_HOST=portainer.grenka.uz
      - LETSENCRYPT_EMAIL=haratian.gena@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - tf_idf_network
      - nginx_proxy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - VIRTUAL_HOST=pgadmin.grenka.uz
      - LETSENCRYPT_HOST=pgadmin.grenka.uz
      - LETSENCRYPT_EMAIL=haratian.gena@gmail.com
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tf_idf_network
      - nginx_proxy
    restart: always

volumes:
  alembic-data:
  postgres_data:
  static-data:
  portainer_data:
  pgadmin_data:

networks:
  tf_idf_network:
    driver: bridge
  nginx_proxy:
    external: true
