version: '3.8'

services:
  db:
      image: postgres
      container_name: tf_idf-postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: tf_idf
      ports:
        - "5435:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: tf_idf_lesta
    ports:
      - "8001:8000"

    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tf_idf
      - DB_USER=postgres
      - DB_PASS=postgres
      
    volumes:
      - static-data:/app/static
    
    depends_on:
      - db
      - redis_service

    command: >
      sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips=*"

  redis_service:
    image: redis
    container_name: tf_idf-redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  static-data:
  redis_data: