services:
  db:
    image: postgres
    container_name: tf_idf-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tf_idf_network

  web:
    build: .
    container_name: tf_idf_lesta
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ALLOW_ORIGINS=${ALLOW_ORIGINS}
    volumes:
      - alembic-data:/app/alembic/versions
      - static-data:/app/static
    depends_on:
      - db
    command: >
      sh -c "/wait-for-it.sh db:5432 -- alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips=${ALLOW_ORIGINS}"
    networks:
      - tf_idf_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - tf_idf_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"  # pgAdmin будет доступен на http://<ip>:5050
    depends_on:
      - db
    networks:
      - tf_idf_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  alembic-data:
  postgres_data:
  static-data:
  portainer_data:
  pgadmin_data:

networks:
  tf_idf_network:
    driver: bridge
