services:
  db:
    image: postgres
    container_name: tf_idf-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tf_idf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tf_idf_network

  web:
    build: .
    container_name: tf_idf_lesta
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tf_idf
      - DB_USER=postgres
      - DB_PASS=postgres
      - ALLOW_ORIGINS=*
    volumes:
      - alembic-data:/app/alembic/versions
      - static-data:/app/static
    depends_on:
      - db
    command: >
      sh -c "/wait-for-it.sh db:5432 -- alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips=*"
    networks:
      - tf_idf_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - tf_idf_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: haratian.gena@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # pgAdmin будет доступен на http://<ip>:5050
    depends_on:
      - db
    networks:
      - tf_idf_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  alembic-data:
  postgres_data:
  static-data:
  portainer_data:
  pgadmin_data:

networks:
  tf_idf_network:
    driver: bridge
